apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: logging
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: lank8s.cn/sig-storage/nfs-subdir-external-provisioner:v4.0.2 # 镜像替换为了国内可以拉取到的地址
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner # storageClass 的 provisioner 必须要使用这个名称
            - name: NFS_SERVER
              value: 172.16.168.3 # 替换为你自己的 NFS 服务器地址
            - name: NFS_PATH
              value: /data # 替换为你自己的 NFS 服务器共享目录
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.168.3 # 替换为你自己的 NFS 服务器
            path: /data # 替换为你自己的 NFS 服务器共享目录
