apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging # 替换为你自己的 namespace 
spec:
  selector:
    app: kibana
  type: NodePort # 使用 NodePort 暴露端口
  ports:
    - port: 8080
      targetPort: 5601
      nodePort: 30000  # 使用 NodePort 暴露端口，可以替换你想用的端口（30000-32767之间）