apiVersion: v1
kind: Service
metadata:
  namespace: logging # 命名空间需要替换
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None # Headless Service
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node